export const LOAD_WORKSPACES_REQUEST = "LOAD_WORKSPACES_REQUEST";
export const LOAD_WORKSPACES_SUCCESSED = "LOAD_WORKSPACES_SUCCESSED";
export const LOAD_WORKSPACES_FAILURE = "LOAD_WORKSPACES_FAILURE";

export const LOAD_WORKSPACE_BY_ID_REQUEST = "LOAD_WORKSPACE_BY_ID_REQUEST";
export const LOAD_WORKSPACE_BY_ID_SUCCESSED = "LOAD_WORKSPACE_BY_ID_SUCCESSED";
export const LOAD_WORKSPACE_BY_ID_FAILURE = "LOAD_WORKSPACE_BY_ID_FAILURE";

export const LOAD_DEFAULT_WORKSPACE_REQUEST = "LOAD_DEFAULT_WORKSPACE_REQUEST";
export const LOAD_DEFAULT_WORKSPACE_SUCCESSED =
  "LOAD_DEFAULT_WORKSPACE_SUCCESSED";
export const LOAD_DEFAULT_WORKSPACE_FAILURE = "LOAD_DEFAULT_WORKSPACE_FAILURE";

export const ADD_WORKSPACE_REQUEST = "ADD_WORKSPACE_REQUEST";
export const ADD_WORKSPACE_SUCCESSED = "ADD_WORKSPACE_SUCCESSED";
export const ADD_WORKSPACE_FAILURE = "ADD_WORKSPACE_FAILURE";

export const JOIN_WORKSPACE_REQUEST = "JOIN_WORKSPACE_REQUEST";
export const JOIN_WORKSPACE_SUCCESSED = "JOIN_WORKSPACE_SUCCESSED";
export const JOIN_WORKSPACE_FAILURE = "JOIN_WORKSPACE_FAILURE";
