// export const LOAD_WORKSPACES_REQUEST = "LOAD_WORKSPACES_REQUEST";
// export const LOAD_WORKSPACES_SUCCESSED = "LOAD_WORKSPACES_SUCCESSED";
// export const LOAD_WORKSPACES_FAILURE = "LOAD_WORKSPACES_FAILURE";

// export const LOAD_WORKSPACE_BY_ID_REQUEST = "LOAD_WORKSPACE_BY_ID_REQUEST";
// export const LOAD_WORKSPACE_BY_ID_SUCCESSED = "LOAD_WORKSPACE_BY_ID_SUCCESSED";
// export const LOAD_WORKSPACE_BY_ID_FAILURE = "LOAD_WORKSPACE_BY_ID_FAILURE";

// export const LOAD_DEFAULT_WORKSPACE_REQUEST = "LOAD_DEFAULT_WORKSPACE_REQUEST";
// export const LOAD_DEFAULT_WORKSPACE_SUCCESSED =
//   "LOAD_DEFAULT_WORKSPACE_SUCCESSED";
// export const LOAD_DEFAULT_WORKSPACE_FAILURE = "LOAD_DEFAULT_WORKSPACE_FAILURE";

// export const ADD_WORKSPACE_REQUEST = "ADD_WORKSPACE_REQUEST";
// export const ADD_WORKSPACE_SUCCESSED = "ADD_WORKSPACE_SUCCESSED";
// export const ADD_WORKSPACE_FAILURE = "ADD_WORKSPACE_FAILURE";

// export const JOIN_WORKSPACE_REQUEST = "JOIN_WORKSPACE_REQUEST";
// export const JOIN_WORKSPACE_SUCCESSED = "JOIN_WORKSPACE_SUCCESSED";
// export const JOIN_WORKSPACE_FAILURE = "JOIN_WORKSPACE_FAILURE";

// export const LOGIN_REQUEST = "LOGIN_REQUEST";
// export const LOGIN_SUCCESSED = "LOGIN_SUCCESSED";
// export const LOGIN_FAILURE = "LOGIN_FAILURE";

// export const LOGOUT = "LOGOUT";

// export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
// export const LOAD_USER_SUCCESSED = "LOAD_USER_SUCCESSED";
// export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

// //Action of Task reducer

// export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
// export const UPDATE_TASK_SUCCESSED = "UPDATE_TASK_SUCCESSED";
// export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";

// export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
// export const DELETE_TASK_SUCCESSED = "DELETE_TASK_SUCCESSED";
// export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

// export const UPDATE_CHILD_TASK_REQUEST = "UPDATE_CHILD_TASK_REQUEST";
// export const UPDATE_CHILD_TASK_SUCCESSED = "UPDATE_CHILD_TASK_SUCCESSED";
// export const UPDATE_CHILD_TASK_FAILURE = "UPDATE_CHILD_TASK_FAILURE";

// export const DELETE_CHILD_TASK_REQUEST = "DELETE_CHILD_TASK_REQUEST";
// export const DELETE_CHILD_TASK_SUCCESSED = "DELETE_CHILD_TASK_SUCCESSED";
// export const DELETE_CHILD_TASK_FAILURE = "DELETE_CHILD_TASK_FAILURE";

// export const LOAD_TASKS_REQUEST = "LOAD_TASKS_REQUEST";
// export const LOAD_TASKS_SUCCESSED = "LOAD_TASKS_SUCCESSED";
// export const LOAD_TASKS_FAILURE = "LOAD_TASKS_FAILURE";

// export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
// export const CREATE_TASK_SUCCESSED = "CREATE_TASK_SUCCESSED";
// export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

// export const CREATE_CHILDREN_TASK_REQUEST = "CREATE_CHILDREN_TASK_REQUEST";
// export const CREATE_CHILDREN_TASK_SUCCESSED = "CREATE_CHILDREN_TASK_SUCCESSED";
// export const CREATE_CHILDREN_TASK_FAILURE = "CREATE_CHILDREN_TASK_FAILURE";

// export const MARK_COMPLETED_TASK_REQUEST = "MARK_COMPLETED_TASK_REQUEST";
// export const MARK_COMPLETED_TASK_SUCCESSED = "MARK_COMPLETED_TASK_SUCCESSED";
// export const MARK_COMPLETED_TASK_FAILURE = "MARK_COMPLETED_TASK_FAILURE";

// export const SEND_LESSON_REQUEST = "SEND_LESSON_REQUEST";
// export const SEND_LESSON_SUCCESSED = "SEND_LESSON_SUCCESSED";
// export const SEND_LESSON_FAILURE = "SEND_LESSON_FAILURE";

// export const DELETE_UPLOADED_FILE_REQUEST = "DELETE_UPLOADED_FILE_REQUEST";
// export const DELETE_UPLOADED_FILE_SUCCESSED = "DELETE_UPLOADED_FILE_SUCCESSED";
// export const DELETE_UPLOADED_FILE_FAILURE = "DELETE_UPLOADED_FILE_FAILURE";

// // TaskUser Action

// export const LOAD_TASK_USERS_REQUEST = "LOAD_TASK_USERS_REQUEST";
// export const LOAD_TASK_USERS_SUCCESSED = "LOAD_TASK_USERS_SUCCESSED";
// export const LOAD_TASK_USERS_FAILURE = "LOAD_TASK_USERS_FAILURE";

// export const LOAD_TASK_USER_REQUEST = "LOAD_TASK_USER_REQUEST";
// export const LOAD_TASK_USER_SUCCESSED = "LOAD_TASK_USER_SUCCESSED";
// export const LOAD_TASK_USER_FAILURE = "LOAD_TASK_USER_FAILURE";

// export const ROLE_USER = "USER";
// export const ROLE_LEADER = "LEADER";
// export const ROLE_ADMIN = "ADMIN";

// //ADMIN=================================================================GG
// export const LOAD_ADMIN_USERS_REQUEST = "LOAD_ADMIN_USERS_REQUEST";
// export const LOAD_ADMIN_USERS_SUCCESSED = "LOAD_ADMIN_USERS_SUCCESSED";
// export const LOAD_ADMIN_USERS_FAILURE = "LOAD_ADMIN_USERS_FAILURE";

// export const LOAD_ADMIN_WORKSPACES_REQUEST = "LOAD_ADMIN_WORKSPACES_REQUEST";
// export const LOAD_ADMIN_WORKSPACES_SUCCESSED =
//   "LOAD_ADMIN_WORKSPACES_SUCCESSED";
// export const LOAD_ADMIN_WORKSPACES_FAILURE = "LOAD_ADMIN_WORKSPACES_FAILURE";

// export const LOAD_ADMIN_TASKS_REQUEST = "LOAD_ADMIN_TASKS_REQUEST";
// export const LOAD_ADMIN_TASKS_SUCCESSED = "LOAD_ADMIN_TASKS_SUCCESSED";
// export const LOAD_ADMIN_TASKS_FAILURE = "LOAD_ADMIN_TASKS_FAILURE";

// export const SET_ADMIN_USER = "SET_ADMIN_USER";
// export const ADD_ADMIN_USER = "ADD_ADMIN_USER";

// export const SET_ADMIN_IS_CHOICE_USER = "SET_ADMIN_IS_CHOICE_USER";
// export const SET_ADMIN_IS_CHANGED_USER = "SET_ADMIN_IS_CHANGED_USER";

// export const UPDATE_OR_ADD_ADMIN_USERS_REQUEST =
//   "UPDATE_OR_ADD_ADMIN_USERS_REQUEST";
// export const UPDATE_OR_ADD_ADMIN_USERS_SUCCESSED =
//   "UPDATE_OR_ADD_ADMIN_USERS_SUCCESSED";
// export const UPDATE_OR_ADD_ADMIN_USERS_FAILURE =
//   "UPDATE_OR_ADD_ADMIN_USERS_FAILURE";

// export const DELETE_ADMIN_USERS_REQUEST = "DELETE_ADMIN_USERS_REQUEST";
// export const DELETE_ADMIN_USERS_SUCCESSED = "DELETE_ADMIN_USERS_SUCCESSED";
// export const DELETE_ADMIN_USERS_FAILURE = "DELETE_ADMIN_USERS_FAILURE";

// export const LOAD_TASK_STATISTIC_REQUEST = "LOAD_TASK_STATISTIC_REQUEST";
// export const LOAD_TASK_STATISTIC_SUCCESSED = "LOAD_TASK_STATISTIC_SUCCESSED";
// export const LOAD_TASK_STATISTIC_FAILURE = "LOAD_TASK_STATISTIC_FAILURE";
