export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESSED = "UPDATE_TASK_SUCCESSED";
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESSED = "DELETE_TASK_SUCCESSED";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

export const UPDATE_CHILD_TASK_REQUEST = "UPDATE_CHILD_TASK_REQUEST";
export const UPDATE_CHILD_TASK_SUCCESSED = "UPDATE_CHILD_TASK_SUCCESSED";
export const UPDATE_CHILD_TASK_FAILURE = "UPDATE_CHILD_TASK_FAILURE";

export const DELETE_CHILD_TASK_REQUEST = "DELETE_CHILD_TASK_REQUEST";
export const DELETE_CHILD_TASK_SUCCESSED = "DELETE_CHILD_TASK_SUCCESSED";
export const DELETE_CHILD_TASK_FAILURE = "DELETE_CHILD_TASK_FAILURE";

export const LOAD_TASKS_REQUEST = "LOAD_TASKS_REQUEST";
export const LOAD_TASKS_SUCCESSED = "LOAD_TASKS_SUCCESSED";
export const LOAD_TASKS_FAILURE = "LOAD_TASKS_FAILURE";

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESSED = "CREATE_TASK_SUCCESSED";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

export const CREATE_CHILDREN_TASK_REQUEST = "CREATE_CHILDREN_TASK_REQUEST";
export const CREATE_CHILDREN_TASK_SUCCESSED = "CREATE_CHILDREN_TASK_SUCCESSED";
export const CREATE_CHILDREN_TASK_FAILURE = "CREATE_CHILDREN_TASK_FAILURE";

export const MARK_COMPLETED_TASK_REQUEST = "MARK_COMPLETED_TASK_REQUEST";
export const MARK_COMPLETED_TASK_SUCCESSED = "MARK_COMPLETED_TASK_SUCCESSED";
export const MARK_COMPLETED_TASK_FAILURE = "MARK_COMPLETED_TASK_FAILURE";

export const SEND_LESSON_REQUEST = "SEND_LESSON_REQUEST";
export const SEND_LESSON_SUCCESSED = "SEND_LESSON_SUCCESSED";
export const SEND_LESSON_FAILURE = "SEND_LESSON_FAILURE";

export const DELETE_UPLOADED_FILE_REQUEST = "DELETE_UPLOADED_FILE_REQUEST";
export const DELETE_UPLOADED_FILE_SUCCESSED = "DELETE_UPLOADED_FILE_SUCCESSED";
export const DELETE_UPLOADED_FILE_FAILURE = "DELETE_UPLOADED_FILE_FAILURE";
