export const LOAD_TASK_USERS_REQUEST = "LOAD_TASK_USERS_REQUEST";
export const LOAD_TASK_USERS_SUCCESSED = "LOAD_TASK_USERS_SUCCESSED";
export const LOAD_TASK_USERS_FAILURE = "LOAD_TASK_USERS_FAILURE";

export const LOAD_TASK_USER_REQUEST = "LOAD_TASK_USER_REQUEST";
export const LOAD_TASK_USER_SUCCESSED = "LOAD_TASK_USER_SUCCESSED";
export const LOAD_TASK_USER_FAILURE = "LOAD_TASK_USER_FAILURE";
