export const LOAD_ADMIN_USERS_REQUEST = "LOAD_ADMIN_USERS_REQUEST";
export const LOAD_ADMIN_USERS_SUCCESSED = "LOAD_ADMIN_USERS_SUCCESSED";
export const LOAD_ADMIN_USERS_FAILURE = "LOAD_ADMIN_USERS_FAILURE";

export const LOAD_ADMIN_WORKSPACES_REQUEST = "LOAD_ADMIN_WORKSPACES_REQUEST";
export const LOAD_ADMIN_WORKSPACES_SUCCESSED =
  "LOAD_ADMIN_WORKSPACES_SUCCESSED";
export const LOAD_ADMIN_WORKSPACES_FAILURE = "LOAD_ADMIN_WORKSPACES_FAILURE";

export const LOAD_ADMIN_TASKS_REQUEST = "LOAD_ADMIN_TASKS_REQUEST";
export const LOAD_ADMIN_TASKS_SUCCESSED = "LOAD_ADMIN_TASKS_SUCCESSED";
export const LOAD_ADMIN_TASKS_FAILURE = "LOAD_ADMIN_TASKS_FAILURE";

export const SET_ADMIN_USER = "SET_ADMIN_USER";
export const ADD_ADMIN_USER = "ADD_ADMIN_USER";

export const SET_ADMIN_IS_CHOICE_USER = "SET_ADMIN_IS_CHOICE_USER";
export const SET_ADMIN_IS_CHANGED_USER = "SET_ADMIN_IS_CHANGED_USER";

export const UPDATE_OR_ADD_ADMIN_USERS_REQUEST =
  "UPDATE_OR_ADD_ADMIN_USERS_REQUEST";
export const UPDATE_OR_ADD_ADMIN_USERS_SUCCESSED =
  "UPDATE_OR_ADD_ADMIN_USERS_SUCCESSED";
export const UPDATE_OR_ADD_ADMIN_USERS_FAILURE =
  "UPDATE_OR_ADD_ADMIN_USERS_FAILURE";

export const DELETE_ADMIN_USERS_REQUEST = "DELETE_ADMIN_USERS_REQUEST";
export const DELETE_ADMIN_USERS_SUCCESSED = "DELETE_ADMIN_USERS_SUCCESSED";
export const DELETE_ADMIN_USERS_FAILURE = "DELETE_ADMIN_USERS_FAILURE";

export const LOAD_TASK_STATISTIC_REQUEST = "LOAD_TASK_STATISTIC_REQUEST";
export const LOAD_TASK_STATISTIC_SUCCESSED = "LOAD_TASK_STATISTIC_SUCCESSED";
export const LOAD_TASK_STATISTIC_FAILURE = "LOAD_TASK_STATISTIC_FAILURE";
